### ISSUE TITLE
How can I change order of right toolbar blocks ?

### ISSUE THREAD

**Issue by sergeynilov** [jawad-topdot/laravel-grapesjs#38]
Hello,
using laravel-grapesjs "3.3.0" I have several blocks of data “Extra”, "Basick", “Forms”, “Templates” and custom blocks, 
which are based on “grapesjs-tailwind”. If there is a way to change order of these blocks ? 
1) I need to show custom blocks at top and “Extra”, "Basick", “Forms” below...
2) I need to show some custom blocks with opened elements , but all “Extra”, "Basick", “Forms” closed...

How can I do it ?

Thanks!

**Comment by sergeynilov** [comment]
As functionality I request is not standart for laravel-grapesjs plugin could you please give a hint in which files can I apply modifications ? I have some expierence in manuall editing of grapesjs javascript files....

**Comment by jd-dotlogics** [comment]
@sergeynilov you can simply create a new plugin and add your code to that plugin.

I've explained how to add the plugin [https://github.com/jd-dotlogics/laravel-grapesjs/issues/36#issuecomment-1165350859](here)
